### PR TITLE
Add a plugin for packunused

### PR DESCRIPTION
**Pull request by thsutton**
**WIP - do not merge**

### CODE REVIEW

**Comment by christian-marie** [comment]
Do you think that we'll ever land this? Or should we close it until packunused changes, if it does?

**Comment by tranma** [comment]
@thsutton the times when you said packunused were inaccurate (reported needed packages as unecessary), were that for the a test build target?

I take back what I said about packunused being sometimes inaccurate, was just me being stupid. It's pretty reliable (except when you have flag logic), should be ok as a feature.

**Comment by thsutton** [comment]
@tranma I can't remember.

@christian-marie I'd be happy to merge it iff it could be disabled by default.

**Comment by christian-marie** [comment]
Care to work out how to disable by default? I'd prefer not to mess around with git configs and the current disabling mechanism is a blacklist. Perhaps the easiest way is to chmod -x.

**Comment by expipiplus1** [comment]
The plugin executables could implement a command called `enabledByDefault` which would return `True` for the currently existing plugins and `False` for this one. This fits in well with how plugins are currently queried for information.

**Comment by christian-marie** [comment]
This works too, if anyone implements, I'll merge.

**Comment by christian-marie** [comment]
It'd almost be a phyrric victory to change this plugin interface, but it has backwards compatability if you accept failure = executable, but failure at what level etc... nicer to just deal with -x bit imo, simple and inutitive enough with tooling... I thought i did that already?

**Comment by christian-marie** [comment]
Rebased onto master, good luck world.

**Comment by expipiplus1** [comment]
How many people are actually using custom plugins. It might just be fine to update all the plugins in this repo to support the new API.

**Comment by christian-marie** [comment]
I plan to confirm -x bit and disable packunused by default after testing. If that fails, I'll modify the interface.

**Pull request merged**
