### PR TITLE
Allow using no vcs system

### PR DESCRIPTION
**Pull request by expipiplus1**
This PR seems to have been lost in the recent repo shuffling.

### CODE REVIEW

**Comment by christian-marie** [comment]
Thanks! I'm just returning from overseas soon and will be fixing the tests and merging this by next monday.

**Comment by christian-marie** [comment]
I want to clean up the options parsing code here, to make it possible for > 2 VCS to be supported. Do you mind if I drop --no-git? I'd replace it with --vcs null, probably.

**Comment by expipiplus1** [comment]
Sure, that makes sense.

**Comment by christian-marie** [comment]
OK, I'll get this done this weekend.

**Comment by expipiplus1** [comment]
Thanks!

**Pull request merged**
